query GetTodos {
  todos {
    ...todo
  }
}

query GetTodo($id: ID!) {
  todo(id: $id) {
    ...todo
  }
}

mutation CreateTodo($values: TodoInput!) {
  createTodo(values: $values) {
    ...todo
  }
}

mutation DeleteTodo($id: ID!) {
  deleteTodo(id: $id) {
    ...todo
  }
}

mutation UpdateTodo($id: ID!, $values: TodoInput!) {
  updateTodo(id: $id, values: $values) {
    ...todo
  }
}

fragment todo on Todo {
  id
  title
  notes
  isCompleted
  category
}
